Repository MRita443/RailwayManagement, pull requests merged in 2023-04, with the labels that each got.

#2 added findEndOfLine method
  src/graph.cpp
  src/graph.h
Labels: enhancement

#5 Data initialization
  CMakeLists.txt
  src/dataRepository.cpp
  src/dataRepository.h
  src/edge.cpp
  src/edge.h
  src/graph.cpp
  src/graph.h
  src/menu.cpp
  src/menu.h
  src/station.cpp
  src/station.h
  src/vertex.cpp
  src/vertex.h
Labels: enhancement

#7 Feature/edmonds karp variations
  src/graph.cpp
  src/graph.h
Labels: documentation, enhancement, question

#8 Fixed edmonds-karp with residual graph addition
  src/edge.cpp
  src/edge.h
  src/graph.cpp
  src/graph.h
  src/menu.cpp
  src/menu.h
  src/vertex.cpp
  src/vertex.h
Labels: bug, enhancement

#9 feature/top-partitions-methods
  src/graph.cpp
  src/graph.h
  src/menu.h
Labels: enhancement

#10 Min cost
  src/edge.cpp
  src/edge.h
  src/graph.cpp
  src/graph.h
  src/menu.cpp
Labels: enhancement

#11 Menu finalization
  src/graph.cpp
  src/graph.h
  src/menu.cpp
  src/menu.h
Labels: documentation, enhancement
